version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
    - "127.0.0.1:9200:9200"
    environment:
      TZ: "Europe/Berlin"
      http.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
    restart: unless-stopped
    mem_limit: 1024m
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
    - "127.0.0.1:5601:5601"
    environment:
      TZ: "Europe/Berlin"
    restart: unless-stopped
    mem_limit: 256m
  elasticpy:
    image: grolland/elasticpy:1
    build: .
    ports:
    - "127.0.0.1:5601:5601"
    environment:
      TZ: "Europe/Berlin"
    restart: never
    mem_limit: 128m

